<<<<<<< HEAD:Django_PJT1/accounts/migrations/0002_auto_20191128_0013.py
# Generated by Django 2.2.7 on 2019-11-27 15:13
=======
# Generated by Django 2.2.7 on 2019-11-27 23:53
>>>>>>> 1abc19eb79c7cf983947ff3c93a7d893a79950ed:Django_PJT1/accounts/migrations/0002_auto_20191128_0853.py

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD:Django_PJT1/accounts/migrations/0002_auto_20191128_0013.py
        ('auth', '0011_update_proxy_permissions'),
        ('movies', '0001_initial'),
        ('accounts', '0001_initial'),
=======
        ('movies', '0001_initial'),
        ('accounts', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
>>>>>>> 1abc19eb79c7cf983947ff3c93a7d893a79950ed:Django_PJT1/accounts/migrations/0002_auto_20191128_0853.py
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_genres',
            field=models.ManyToManyField(related_name='like_users', to='movies.Genre'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
