# Generated by Django 2.2.7 on 2019-11-27 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191126_2139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Damgle',
        ),
    ]
